Test integration
FCP-MockFogLoad/MockFogLight pull request #7
Opened 2020-03-09 19:55 UTC by jahandaniyal

2020-03-09 20:28 UTC, MaxF12 commented on mockfog_application/tasks/check_dependencies.yml
> +#  shell: sudo yum install emqx -y
Remove out commented code

2020-03-09 20:28 UTC, MaxF12 commented on mockfog_application/tasks/deploy.yml
> +#  shell: docker run -d -m256M --cpus 2 -it --rm -p {{ ports }} {{ docker_image }}
This too

2020-03-09 20:28 UTC, MaxF12 commented on testbed/common.py
> +    #     del g.node[node]['app_configs']
Same

2020-03-09 20:28 UTC, MaxF12 commented on testbed/common.py
> +    # assert 'timeout' in config
+1

2020-03-09 20:28 UTC, MaxF12 commented on testbed/generate_testbed_definition.py
> +# topologies.simple_topology(g)
+1

2020-03-10 19:12 UTC, renderfehler requested changes

2020-03-10 19:12 UTC, renderfehler commented on mapping.json
> +{"ip": "52.29.200.79", "name": "generator2" },
What is this file for?

2020-03-10 19:12 UTC, renderfehler commented on mapping.yml
> +- ip: 3.120.111.80
What is this file for? Isn't this file generated each time?

2020-03-10 19:12 UTC, renderfehler commented on mockfog_agent/telegraf.conf
> +[[outputs.influxdb]]
Is this still included? We don't need this anymore.

2020-03-10 19:12 UTC, renderfehler commented on mockfog_application/tasks/check_dependencies.yml
> +#
Remove the comments?

2020-03-10 19:12 UTC, renderfehler commented on mockfog_application/tasks/deploy_telegraf.yml
> +---
Do we want to keep this?

2020-03-10 19:12 UTC, renderfehler commented on mockfog_application/tasks/main.yml
> +- import_tasks: deploy_telegraf.yml
Here again deploy telegraf

2020-03-10 19:12 UTC, renderfehler commented on setup.py
> +import os
This should be gone too. The agent should be a single file now.

2020-03-10 19:12 UTC, renderfehler commented on testbed/generate_topologies.py
> +    # the role is attached as tag to the AWS instance and can be used to run tasks only on machines with a certain role (see mockfog_application.yml notebook)
indentation

2020-03-10 19:12 UTC, renderfehler commented on testbed/testbed_definition.yml
>  - type: machine
Add all generated files to .gitignore

2020-03-10 19:12 UTC, renderfehler commented on testbed/application_definition.yml
> +--- {}
What is this for?

2020-03-11 14:10 UTC, renderfehler approved these changes

2020-03-11 15:09 UTC, merged